spring:
  datasource:
    url: jdbc:h2:file:./data/testdb   # baza w pliku, zachowuje dane między restartami
    driver-class-name: org.h2.Driver
    username: sa
    password: dupa
  jpa:
    hibernate:
      ddl-auto: update    # update zachowa istniejące tabele i doda nowe
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#michalinka pozdrawia <3
server:
  servlet:
    context-path: /   # wszystkie endpointy pod /
  port: 8081         # możesz zmienić port jeśli chcesz
