spring:
  #profiles:
   # active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: dupa
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  default-consumes-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
