 #spring:
  #datasource:
   # url: jdbc:postgresql://localhost:5432/book_lover_community
    #username: username
    #password: password
    #driver-class-name: org.postgresql.Driver
  #jpa:
   # hibernate:
    #  ddl-auto: update
    #show-sql: false
    #properties:
     # hibernate:
     #   format_sql: true
    #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
  #mail:
   # host: localhost
    #port: 1025
    #username: neon
    #password: neon
    #properties:
    #  mail:
     #   smtp:
      #    trust: "*"
       # auth: true
        #starttls:
  #        enable: true
  #      connectiontimeout: 5000
  #      timeout: 3000
  #      writetimeout: 5000

#application:
 # security:
  #  jwt:
   #   secret-key: dhasud
    #  expiration: 8640000
